/*LOAD DATA FROM SAL_CL TO SAL*/

CREATE OR REPLACE PACKAGE PKG_FROM_SAL_CL_TO_SAL
AS
   PROCEDURE LOAD_TO_SAL_USERS;
   PROCEDURE LOAD_TO_SAL_TRANSACTIONS;
   PROCEDURE LOAD_TO_SAL_OPER_TYPE_MET;
   PROCEDURE LOAD_TO_SAL_OPER_TYPE;
   PROCEDURE LOAD_TO_SAL_CL_CURRENCY;
END;