SELECT table_name FROM user_tables;

SELECT * FROM FCT_TRANSACTIONS
SELECT * FROM U_STR_DATA.DIM_OPERATION_TYPES_METHODS
SELECT * FROM U_STR_DATA.DIM_OPERATION_TYPES
SELECT * FROM U_STR_DATA.DIM_CURRENCY_SCD
SELECT * FROM U_STR_DATA.DIM_USERS 

SELECT * FROM dba_tab_partitions WHERE table_name = 'FCT_TRANSACTIONS';

SELECT *FROM FCT_TRANSACTIONS partition (p12);

SELECT MAX(EVENT_DT) from FCT_TRANSACTIONS
