/* RUN PACKAGE TO LAD DATA FROM SAL_CL TO SAL */
--Alter Session Enable Parallel DML;

BEGIN
  PKG_FROM_SAL_CL_TO_SAL.LOAD_TO_SAL_USERS;
  PKG_FROM_SAL_CL_TO_SAL.LOAD_TO_SAL_TRANSACTIONS;
  PKG_FROM_SAL_CL_TO_SAL.LOAD_TO_SAL_OPER_TYPE_MET;
  PKG_FROM_SAL_CL_TO_SAL.LOAD_TO_SAL_OPER_TYPE;
  PKG_FROM_SAL_CL_TO_SAL.LOAD_TO_SAL_CL_CURRENCY;
   
END;

