DROP TABLE U_STG.LC_CUSTOMERS CASCADE CONSTRAINTS;

CREATE TABLE U_STG.LC_CUSTOMERS
(
  CUSTOMER_ID      NUMBER(20)                   NOT NULL,
  CUST_CODE        VARCHAR2(20 BYTE),
  CUST_DESC        VARCHAR2(70 BYTE),
  LOCALIZATION_ID  NUMBER(22)                   NOT NULL,
  INSERT_DT        DATE,
  UPDATE_DT        DATE
)
TABLESPACE TS_STG_DATA_01
;


GRANT INSERT, SELECT, UPDATE ON U_STG.LC_CUSTOMERS TO U_DW_EXT_REFERENCES;
