ALTER TABLE U_STG.T_CUSTOMERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE U_STG.T_CUSTOMERS CASCADE CONSTRAINTS;

CREATE TABLE U_STG.T_CUSTOMERS
(
  CUSTOMER_ID     NUMBER(20)                    NOT NULL,
  CUST_CODE       VARCHAR2(20 BYTE),
  GEO_ID          NUMBER(20),
  CUST_STATUS_ID  NUMBER(20),
  INSERT_DT       DATE,
  UPDATE_DT       DATE
)
TABLESPACE TS_STG_DATA_01
;


CREATE UNIQUE INDEX U_STG.T_CUSTOMERS_PK ON U_STG.T_CUSTOMERS
(CUSTOMER_ID)
LOGGING
TABLESPACE TS_STG_DATA_01
;


ALTER TABLE U_STG.T_CUSTOMERS ADD (
  CONSTRAINT T_CUSTOMERS_PK
 PRIMARY KEY
 (CUSTOMER_ID)
    USING INDEX 
    TABLESPACE TS_STG_DATA_01
);

GRANT INSERT, SELECT, UPDATE ON U_STG.T_CUSTOMERS TO U_DW_EXT_REFERENCES;
