ALTER TABLE U_STG.T_CUSTOMERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE U_STG.T_CUSTOMERS CASCADE CONSTRAINTS;

CREATE TABLE U_STG.T_CUSTOMERS
(
  CUSTOMER_ID     NUMBER(20)                    NOT NULL,
  CUST_CODE       VARCHAR2(20 BYTE),
  GEO_ID          NUMBER(20),
  CUST_STATUS_ID  NUMBER(20),
  INSERT_DT       DATE,
  UPDATE_DT       DATE
)
TABLESPACE TS_STG_DATA_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX U_STG.T_CUSTOMERS_PK ON U_STG.T_CUSTOMERS
(CUSTOMER_ID)
LOGGING
TABLESPACE TS_STG_DATA_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE U_STG.T_CUSTOMERS ADD (
  CONSTRAINT T_CUSTOMERS_PK
 PRIMARY KEY
 (CUSTOMER_ID));

ALTER TABLE U_STG.T_CUSTOMERS ADD (
  CONSTRAINT T_CUSTOMERS_R01 
 FOREIGN KEY (GEO_ID) 
 REFERENCES U_STG.T_GEO_OBJECTS (GEO_ID),
  CONSTRAINT T_CUSTOMERS_R02 
 FOREIGN KEY (CUST_STATUS_ID) 
 REFERENCES U_STG.T_CUST_STATUS (STATUS_ID));

GRANT INSERT, SELECT, UPDATE ON U_STG.T_CUSTOMERS TO U_DW_EXT_REFERENCES;
