DROP TABLESPACE TS_SA_DATA_01 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE TS_SA_DATA_01 DATAFILE 
  '/oracle/app/oracle/product/11.2/dbs/db_sa_data_01.dat' SIZE 500M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
NOLOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
