
CREATE TABLESPACE TS_SAL_M1
DATAFILE 'db_sal_m1.dat'
SIZE 20M
 AUTOEXTEND ON NEXT 10M
NOLOGGING
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_SAL_M2
DATAFILE 'db_sal_m2.dat'
SIZE 20M
 AUTOEXTEND ON NEXT 10M
NOLOGGING
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_SAL_M3
DATAFILE 'db_sal_m3.dat'
SIZE 20M
 AUTOEXTEND ON NEXT 10M
NOLOGGING
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_SAL_M4
DATAFILE 'db_sal_m4.dat'
SIZE 20M
 AUTOEXTEND ON NEXT 10M
NOLOGGING
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_SAL_M5
DATAFILE 'db_sal_m5.dat'
SIZE 20M
 AUTOEXTEND ON NEXT 10M
NOLOGGING
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_SAL_M6
DATAFILE 'db_sal_m6.dat'
SIZE 20M
 AUTOEXTEND ON NEXT 10M
NOLOGGING
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_SAL_M7
DATAFILE 'db_sal_m7.dat'
SIZE 20M
 AUTOEXTEND ON NEXT 10M
NOLOGGING
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_SAL_M8
DATAFILE 'db_sal_m8.dat'
SIZE 20M
 AUTOEXTEND ON NEXT 10M
NOLOGGING
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_SAL_M9
DATAFILE 'db_sal_m9.dat'
SIZE 20M
 AUTOEXTEND ON NEXT 10M
NOLOGGING
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_SAL_M10
DATAFILE 'db_sal_m10.dat'
SIZE 20M
 AUTOEXTEND ON NEXT 10M
NOLOGGING
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_SAL_M11
DATAFILE 'db_sal_m11.dat'
SIZE 20M
 AUTOEXTEND ON NEXT 10M
NOLOGGING
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_SAL_M12
DATAFILE 'db_sal_m12.dat'
SIZE 20M
 AUTOEXTEND ON NEXT 10M
NOLOGGING
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_SAL_M13
DATAFILE 'db_sal_m13.dat'
SIZE 20M
 AUTOEXTEND ON NEXT 10M
NOLOGGING
SEGMENT SPACE MANAGEMENT AUTO;

