CREATE TABLE DIM_GEN_PERIOD
(
	PERIOD_SURR_ID  NUMBER(8) NOT NULL,
	PERIOD_ID       NUMBER(8),
	PERIOD_CODE     NUMBER(8),
	PERIOD_DESC     VARCHAR2(200),
	BEGIN_VALUE     DATE,
	END_VALUE       DATE,
	LEVEL_CODE      VARCHAR2(32)
)
;


ALTER TABLE DIM_GEN_PERIOD ADD CONSTRAINT PK_DIM_GEN_PERIOD 
	PRIMARY KEY (PERIOD_SURR_ID)
;

