CREATE TABLE FCT_SALES_DD
(
	EVENT_DT        DATE,
	DEALER_ID       NUMBER(22),
	VEHICLE_ID      NUMBER(22),
	GEO_SURR_ID     NUMBER(22),
	PERIOD_SURR_ID  NUMBER(8),
	FCT_QUANTITY    NUMBER(10),
	FCT_AMOUNT      NUMBER(8,2)
)
;


