CREATE TABLESPACE ts_sb_m
DATAFILE 'db_qpt_sb_m.dat'
SIZE 150M
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;




CREATE TABLESPACE ts_sa_data_01
DATAFILE 'db_qpt_sa_data_01.dat'
SIZE 200M
 AUTOEXTEND ON NEXT 50M
NOLOGGING
DEFAULT NOCOMPRESS
SEGMENT SPACE MANAGEMENT AUTO;