--drop trigger dw.bi_t_cntr_sub_groups
--/
--
--alter table dw.t_cntr_sub_groups
--   drop constraint FK_T_GEO_OBJECTS2CNTR_S_GROUPS
--/
--
--drop table dw.t_cntr_sub_groups cascade constraints
--/

--==============================================================
-- Table: t_cntr_sub_groups                                     
--==============================================================
create table dw.t_cntr_sub_groups 
(
   geo_id               NUMBER(22,0)         not null,
   sub_group_id         NUMBER(22,0)         not null,
   constraint PK_T_CNTR_SUB_GROUPS primary key (geo_id)
)
/

comment on table dw.t_cntr_sub_groups is
'Referense store: Grouping Countries - Sub Groups'
/

comment on column dw.t_cntr_sub_groups.geo_id is
'Unique ID for All Geography objects'
/

comment on column dw.t_cntr_sub_groups.sub_group_id is
'ID Code of Countries Sub Groups'
/

alter table dw.t_cntr_sub_groups
   add constraint FK_T_GEO_OBJECTS2CNTR_S_GROUPS foreign key (geo_id)
      references dw.t_geo_objects (geo_id)
      on delete cascade
      deferrable
/


create trigger dw.bi_t_cntr_sub_groups before insert
on dw.t_cntr_sub_groups for each row
declare
    integrity_error  exception;
    errno            integer;
    errmsg           char(200);
    lc_geo_id      NUMBER := 0;
BEGIN
   IF :new.geo_id IS NOT NULL THEN
      raise_application_error ( -20000
                              , 'Geo_id have to be ''NULL''. New Values will be generated by triger.' );
   END IF;

   INSERT INTO w_geo_objects ( geo_id
                             , geo_type_id
                             , geo_code_id )
        VALUES ( sq_geo_t_id.NEXTVAL
               , 52 --Countries Sub Groups
               , :new.sub_group_id )
     RETURNING geo_id
          INTO :new.geo_id;
--  Errors handling
exception
    when integrity_error then
       raise_application_error(errno, errmsg);
end;
/
