--SA_DATA
CREATE TABLESPACE ts_sa_data_01
DATAFILE 'SOURCES.DAT'
SIZE 100M
 AUTOEXTEND ON NEXT 200M
 SEGMENT SPACE MANAGEMENT AUTO
 LOGGING
 
 --DW_CL
CREATE TABLESPACE ts_dw_cl_data_01
DATAFILE 'CL_SOURCES.DAT'
SIZE 200M
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO
 NOLOGGING

--DW
CREATE TABLESPACE ts_dw_data_01
DATAFILE 'DW_SOURCES.DAT'
SIZE 300M
 AUTOEXTEND ON NEXT 200M
 SEGMENT SPACE MANAGEMENT AUTO
 LOGGING


--SAL_CL
CREATE TABLESPACE  ts_sal_cl_data_01
DATAFILE 'SAL_CL_SOURCES.DAT'
SIZE 100M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO
NOLOGGING



--SAL
CREATE TABLESPACE  ts_sal_data_01
DATAFILE 'SAL_SAL_SOURCES.DAT'
SIZE 300M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO
NOLOGGING