CREATE TABLESPACE SB_MBackUp
DATAFILE 'SB_MBackUp .dat'
SIZE 200M
 AUTOEXTEND ON NEXT 100M
 SEGMENT SPACE MANAGEMENT AUTO;
 
 CREATE USER SB_MBackUp
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE SB_MBackUp;

GRANT CONNECT,RESOURCE TO SB_MBackUp;
grant select any table to SB_MBackUp;

grant unlimited tablespace to SB_MBackUp;