ALTER TABLE U_STG.T_MEASURES
 DROP PRIMARY KEY CASCADE;

DROP TABLE U_STG.T_MEASURES CASCADE CONSTRAINTS;

CREATE TABLE U_STG.T_MEASURES
(
  MEASURE_ID    NUMBER(20)                      NOT NULL,
  MEASURE_CODE  VARCHAR2(10 BYTE),
  MEASURE_DESC  VARCHAR2(70 BYTE),
  INSERT_DT     DATE,
  UPDATE_DT     DATE,
  QUANTITY      NUMBER(10,2)
)
TABLESPACE TS_STG_DATA_01
;


CREATE UNIQUE INDEX U_STG.PK_T_MEASURES ON U_STG.T_MEASURES
(MEASURE_ID)
LOGGING
TABLESPACE TS_STG_DATA_01
;


ALTER TABLE U_STG.T_MEASURES ADD (
  CONSTRAINT PK_T_MEASURES
 PRIMARY KEY
 (MEASURE_ID)
    USING INDEX 
    TABLESPACE TS_STG_DATA_01
  );

GRANT INSERT, SELECT, UPDATE ON U_STG.T_MEASURES TO U_DW_EXT_REFERENCES;
