DROP TABLE U_STG.T_GEO_OBJECT_LINKS CASCADE CONSTRAINTS;

CREATE TABLE U_STG.T_GEO_OBJECT_LINKS
(
  PARENT_GEO_ID  NUMBER(22)                     NOT NULL,
  CHILD_GEO_ID   NUMBER(22)                     NOT NULL,
  LINK_TYPE_ID   NUMBER(22)                     NOT NULL
)
TABLESPACE TS_STG_DATA_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
PARTITION BY LIST (LINK_TYPE_ID)
(  
  PARTITION P_GEO_SYS2CONTINENTS VALUES (1)
    LOGGING
    NOCOMPRESS 
    TABLESPACE TS_STG_DATA_01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION P_CONTINENT2REGIONS VALUES (2)
    LOGGING
    NOCOMPRESS 
    TABLESPACE TS_STG_DATA_01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               ),  
  PARTITION P_REGION2COUNTRIES VALUES (3)
    LOGGING
    NOCOMPRESS 
    TABLESPACE TS_STG_DATA_01
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE U_STG.T_GEO_OBJECT_LINKS IS 'Reference store: All links between Geo Objects';

COMMENT ON COLUMN U_STG.T_GEO_OBJECT_LINKS.PARENT_GEO_ID IS 'Parent objects of Geo_IDs';

COMMENT ON COLUMN U_STG.T_GEO_OBJECT_LINKS.CHILD_GEO_ID IS 'Child objects of Geo_IDs';

COMMENT ON COLUMN U_STG.T_GEO_OBJECT_LINKS.LINK_TYPE_ID IS 'Type of Links, between Geo_IDs';
