DROP USER U_SA_DATA CASCADE;

CREATE USER U_SA_DATA
  IDENTIFIED BY "%PWD%"
  DEFAULT TABLESPACE TS_SA_DATA_01
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for U_SA_DATA 
  GRANT RESOURCE TO U_SA_DATA;
  GRANT CONNECT TO U_SA_DATA;
  ALTER USER U_SA_DATA DEFAULT ROLE ALL;
  -- 3 System Privileges for U_SA_DATA 
  GRANT CREATE ANY VIEW TO U_SA_DATA;
  GRANT CREATE ANY TABLE TO U_SA_DATA;
  GRANT UNLIMITED TABLESPACE TO U_SA_DATA;
  -- 1 Tablespace Quota for U_SA_DATA 
  ALTER USER U_SA_DATA QUOTA UNLIMITED ON TS_SA_DATA_01;
