/* Formatted on 12.08.2013 16:58:17 (QP5 v5.139.911.3011) */
--DROP TABLE fct_wb_fin_countries_mm CASCADE CONSTRAINTS PURGE;

CREATE TABLE fct_wb_fin_countries_mm
(
   event_dt       DATE
 , dim_countries_surr_id NUMBER
 , dim_programs_surr_id NUMBER
 , dim_gen_periods_surr_id NUMBER
 , dim_fin_sources_id NUMBER
 , fin_amount     NUMBER
 , gdp            NUMBER
 , bud_deficit    NUMBER
 , ta_dim_cntr_country_geo_id NUMBER
 , ta_dim_prg_program_id NUMBER
 , ta_dim_prd_period_id_dl NUMBER
 , insert_dt      DATE
 , update_dt      DATE
)
PARTITION BY RANGE (event_dt)
   ( PARTITION y2000
        VALUES LESS THAN
           (TO_DATE ( '01/01/2001'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2001
        VALUES LESS THAN
           (TO_DATE ( '01/01/2002'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2002
        VALUES LESS THAN
           (TO_DATE ( '01/01/2003'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2003
        VALUES LESS THAN
           (TO_DATE ( '01/01/2004'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2004
        VALUES LESS THAN
           (TO_DATE ( '01/01/2005'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2005
        VALUES LESS THAN
           (TO_DATE ( '01/01/2006'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2006
        VALUES LESS THAN
           (TO_DATE ( '01/01/2007'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2007
        VALUES LESS THAN
           (TO_DATE ( '01/01/2008'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2008
        VALUES LESS THAN
           (TO_DATE ( '01/01/2009'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2009
        VALUES LESS THAN
           (TO_DATE ( '01/01/2010'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2010
        VALUES LESS THAN
           (TO_DATE ( '01/01/2011'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2011
        VALUES LESS THAN
           (TO_DATE ( '01/01/2012'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2012
        VALUES LESS THAN
           (TO_DATE ( '01/01/2013'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2013
        VALUES LESS THAN
           (TO_DATE ( '01/01/2014'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2014
        VALUES LESS THAN
           (TO_DATE ( '01/01/2015'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2015
        VALUES LESS THAN
           (TO_DATE ( '01/01/2016'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2016
        VALUES LESS THAN
           (TO_DATE ( '01/01/2017'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2017
        VALUES LESS THAN
           (TO_DATE ( '01/01/2018'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2018
        VALUES LESS THAN
           (TO_DATE ( '01/01/2019'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2019
        VALUES LESS THAN
           (TO_DATE ( '01/01/2020'
                    , 'dd/mm/yyyy' ))
   , PARTITION y2020
        VALUES LESS THAN
           (TO_DATE ( '01/01/2021'
                    , 'dd/mm/yyyy' )) );