CREATE TABLE TMP_COUNTRIES_CITY 
   (  cc_id NUMBER(10), 
   COUNTRY VARCHAR2(100), 
    CAPITAL VARCHAR2(100)
   ) ;

Insert into  TMP_COUNTRIES_CITY   values (1,'Afghanistan','Kabul');
Insert into  TMP_COUNTRIES_CITY   values (2,'Albania','Tirane');
Insert into  TMP_COUNTRIES_CITY   values (3,'Algeria','Algiers');
Insert into  TMP_COUNTRIES_CITY   values (4,'American Samoa','Pago Pago');
Insert into  TMP_COUNTRIES_CITY   values (5,'Andorra','Andorra la Vella');
Insert into  TMP_COUNTRIES_CITY   values (6,'Angola','Luanda');
Insert into  TMP_COUNTRIES_CITY   values (7,'Antigua and Barbuda','W. Indies');
Insert into  TMP_COUNTRIES_CITY   values (8,'Argentina','Buenos Aires');
Insert into  TMP_COUNTRIES_CITY   values (9,'Armenia','Yerevan');
Insert into  TMP_COUNTRIES_CITY   values (10,'Aruba','Oranjestad');
Insert into  TMP_COUNTRIES_CITY   values (11,'Australia','Canberra');
Insert into  TMP_COUNTRIES_CITY   values (12,'Austria','Vienna');
Insert into  TMP_COUNTRIES_CITY   values (13,'Azerbaijan','Baku');
Insert into  TMP_COUNTRIES_CITY   values (14,'Bahamas','Nassau');
Insert into  TMP_COUNTRIES_CITY   values (15,'Bahrain','Manama');
Insert into  TMP_COUNTRIES_CITY   values (16,'Bangladesh','Dhaka');
Insert into  TMP_COUNTRIES_CITY   values (17,'Barbados','Bridgetown');
Insert into  TMP_COUNTRIES_CITY   values (18,'Belarus','Minsk');
Insert into  TMP_COUNTRIES_CITY   values (19,'Belgium','Brussels');
Insert into  TMP_COUNTRIES_CITY   values (20,'Belize','Belmopan');
Insert into  TMP_COUNTRIES_CITY   values (21,'Benin','Porto-Novo');
Insert into  TMP_COUNTRIES_CITY   values (22,'Bhutan','Thimphu');
Insert into  TMP_COUNTRIES_CITY   values (23,'Bolivia (Plurinational State of)','La Paz');
Insert into  TMP_COUNTRIES_CITY   values (24,'Bosnia and Herzegovina','Sarajevo');
Insert into  TMP_COUNTRIES_CITY   values (25,'Botswana','Gaborone');
Insert into  TMP_COUNTRIES_CITY   values (26,'Brazil','Brasilia');
Insert into  TMP_COUNTRIES_CITY   values (27,'British Virgin Islands','Road Town');
Insert into  TMP_COUNTRIES_CITY   values (28,'Brunei Darussalam','Bandar Seri Begawan');
Insert into  TMP_COUNTRIES_CITY   values (29,'Bulgaria','Sofia');
Insert into  TMP_COUNTRIES_CITY   values (30,'Burkina Faso','Ouagadougou');
Insert into  TMP_COUNTRIES_CITY   values (31,'Burundi','Bujumbura');
Insert into  TMP_COUNTRIES_CITY   values (32,'Cambodia','Phnom Penh');
Insert into  TMP_COUNTRIES_CITY   values (33,'Cameroon','Yaounde');
Insert into  TMP_COUNTRIES_CITY   values (34,'Canada','Ottawa');
Insert into  TMP_COUNTRIES_CITY   values (35,'Cape Verde','Praia');
Insert into  TMP_COUNTRIES_CITY   values (36,'Cayman Islands','George Town');
Insert into  TMP_COUNTRIES_CITY   values (37,'Central African Republic','Bangui');
Insert into  TMP_COUNTRIES_CITY   values (38,'Chad','N''Djamena');
Insert into  TMP_COUNTRIES_CITY   values (39,'Chile','Santiago');
Insert into  TMP_COUNTRIES_CITY   values (40,'China','Beijing');
Insert into  TMP_COUNTRIES_CITY   values (41,'Colombia','Bogota');
Insert into  TMP_COUNTRIES_CITY   values (42,'Comoros','Moroni');
Insert into  TMP_COUNTRIES_CITY   values (43,'Congo','Brazzaville');
Insert into  TMP_COUNTRIES_CITY   values (44,'Costa Rica','San Jose');
Insert into  TMP_COUNTRIES_CITY   values (45,'Côte d''Ivoire','Yamoussoukro');
Insert into  TMP_COUNTRIES_CITY   values (46,'Croatia','Zagreb');
Insert into  TMP_COUNTRIES_CITY   values (47,'Cuba','Havana');
Insert into  TMP_COUNTRIES_CITY   values (48,'Cyprus','Nicosia');
Insert into  TMP_COUNTRIES_CITY   values (49,'Czech Republic','Prague');
Insert into  TMP_COUNTRIES_CITY   values (50,'Congo','Kinshasa');
Insert into  TMP_COUNTRIES_CITY   values (51,'Denmark','Copenhagen');
Insert into  TMP_COUNTRIES_CITY   values (52,'Djibouti','Djibouti');
Insert into  TMP_COUNTRIES_CITY   values (53,'Dominica','Roseau');
Insert into  TMP_COUNTRIES_CITY   values (54,'Dominican Republic','Santo Domingo');
Insert into  TMP_COUNTRIES_CITY   values (55,'Ecuador','Quito');
Insert into  TMP_COUNTRIES_CITY   values (56,'Egypt','Cairo');
Insert into  TMP_COUNTRIES_CITY   values (57,'El Salvador','San Salvador');
Insert into  TMP_COUNTRIES_CITY   values (58,'Equatorial Guinea','Malabo');
Insert into  TMP_COUNTRIES_CITY   values (59,'Eritrea','Asmara');
Insert into  TMP_COUNTRIES_CITY   values (60,'Estonia','Tallinn');
Insert into  TMP_COUNTRIES_CITY   values (61,'Ethiopia','Addis Ababa');
Insert into  TMP_COUNTRIES_CITY   values (62,'Falkland Islands (Malvinas)','Stanley');
Insert into  TMP_COUNTRIES_CITY   values (63,'Faeroe Islands','Torshavn');
Insert into  TMP_COUNTRIES_CITY   values (64,'Fiji','Suva');
Insert into  TMP_COUNTRIES_CITY   values (65,'Finland','Helsinki');
Insert into  TMP_COUNTRIES_CITY   values (66,'France','Paris');
Insert into  TMP_COUNTRIES_CITY   values (67,'French Guiana','Cayenne');
Insert into  TMP_COUNTRIES_CITY   values (68,'French Polynesia','Papeete');
Insert into  TMP_COUNTRIES_CITY   values (69,'Gabon','Libreville');
Insert into  TMP_COUNTRIES_CITY   values (70,'Gambia','Banjul');
Insert into  TMP_COUNTRIES_CITY   values (71,'Georgia','T''bilisi');
Insert into  TMP_COUNTRIES_CITY   values (72,'Germany','Berlin');
Insert into  TMP_COUNTRIES_CITY   values (73,'Ghana','Accra');
Insert into  TMP_COUNTRIES_CITY   values (74,'Greece','Athens');
Insert into  TMP_COUNTRIES_CITY   values (75,'Greenland','Nuuk');
Insert into  TMP_COUNTRIES_CITY   values (76,'Guadeloupe','Basse-Terre');
Insert into  TMP_COUNTRIES_CITY   values (77,'Guatemala','Guatemala');
Insert into  TMP_COUNTRIES_CITY   values (78,'Guernsey','St. Peter Port');
Insert into  TMP_COUNTRIES_CITY   values (79,'Guinea','Conakry');
Insert into  TMP_COUNTRIES_CITY   values (80,'Guinea-Bissau','Bissau');
Insert into  TMP_COUNTRIES_CITY   values (81,'Guyana','Georgetown');
Insert into  TMP_COUNTRIES_CITY   values (82,'Haiti','Port-au-Prince');
Insert into  TMP_COUNTRIES_CITY   values (83,'Honduras','Tegucigalpa');
Insert into  TMP_COUNTRIES_CITY   values (84,'Hungary','Budapest');
Insert into  TMP_COUNTRIES_CITY   values (85,'Iceland','Reykjavik');
Insert into  TMP_COUNTRIES_CITY   values (86,'India','New Delhi');
Insert into  TMP_COUNTRIES_CITY   values (87,'Indonesia','Jakarta');
Insert into  TMP_COUNTRIES_CITY   values (88,'Iran (Islamic Republic of)','Tehran');
Insert into  TMP_COUNTRIES_CITY   values (89,'Iraq','Baghdad');
Insert into  TMP_COUNTRIES_CITY   values (90,'Ireland','Dublin');
Insert into  TMP_COUNTRIES_CITY   values (91,'Israel','Jerusalem');
Insert into  TMP_COUNTRIES_CITY   values (92,'Italy','Rome');
Insert into  TMP_COUNTRIES_CITY   values (93,'Jamaica','Kingston');
Insert into  TMP_COUNTRIES_CITY   values (94,'Jordan','Amman');
Insert into  TMP_COUNTRIES_CITY   values (95,'Kazakhstan','Astana');
Insert into  TMP_COUNTRIES_CITY   values (96,'Kenya','Nairobi');
Insert into  TMP_COUNTRIES_CITY   values (97,'Kiribati','Tarawa');
Insert into  TMP_COUNTRIES_CITY   values (98,'Kuwait','Kuwait');
Insert into  TMP_COUNTRIES_CITY   values (99,'Kyrgyzstan','Bishkek');
Insert into  TMP_COUNTRIES_CITY   values (100,'Lao People''s Democratic Republic','Vientiane');
Insert into  TMP_COUNTRIES_CITY   values (101,'Latvia','Riga');
Insert into  TMP_COUNTRIES_CITY   values (102,'Lebanon','Beirut');
Insert into  TMP_COUNTRIES_CITY   values (103,'Lesotho','Maseru');
Insert into  TMP_COUNTRIES_CITY   values (104,'Liberia','Monrovia');
Insert into  TMP_COUNTRIES_CITY   values (105,'Libya','Tripoli');
Insert into  TMP_COUNTRIES_CITY   values (106,'Liechtenstein','Vaduz');
Insert into  TMP_COUNTRIES_CITY   values (107,'Lithuania','Vilnius');
Insert into  TMP_COUNTRIES_CITY   values (108,'Luxembourg','Luxembourg');
Insert into  TMP_COUNTRIES_CITY   values (109,'Madagascar','Antananarivo');
Insert into  TMP_COUNTRIES_CITY   values (110,'Malawi','Lilongwe');
Insert into  TMP_COUNTRIES_CITY   values (111,'Malaysia','Kuala Lumpur');
Insert into  TMP_COUNTRIES_CITY   values (112,'Maldives','Male');
Insert into  TMP_COUNTRIES_CITY   values (113,'Mali','Bamako');
Insert into  TMP_COUNTRIES_CITY   values (114,'Malta','Valletta');
Insert into  TMP_COUNTRIES_CITY   values (115,'Martinique','Fort-de-France');
Insert into  TMP_COUNTRIES_CITY   values (116,'Mauritania','Nouakchott');
Insert into  TMP_COUNTRIES_CITY   values (117,'Mayotte','Mamoudzou');
Insert into  TMP_COUNTRIES_CITY   values (118,'Mexico','Mexico');
Insert into  TMP_COUNTRIES_CITY   values (119,'Micronesia (Federated States of)','Palikir');
Insert into  TMP_COUNTRIES_CITY   values (120,'Mozambique','Maputo');
Insert into  TMP_COUNTRIES_CITY   values (121,'Myanmar','Yangon');
Insert into  TMP_COUNTRIES_CITY   values (122,'Namibia','Windhoek');
Insert into  TMP_COUNTRIES_CITY   values (123,'Nepal','Kathmandu');
Insert into  TMP_COUNTRIES_CITY   values (124,'Netherlands','Amsterdam');
Insert into  TMP_COUNTRIES_CITY   values (125,'New Caledonia','Noumea');
Insert into  TMP_COUNTRIES_CITY   values (126,'New Zealand','Wellington');
Insert into  TMP_COUNTRIES_CITY   values (127,'Nicaragua','Managua');
Insert into  TMP_COUNTRIES_CITY   values (128,'Niger','Niamey');
Insert into  TMP_COUNTRIES_CITY   values (129,'Nigeria','Abuja');
Insert into  TMP_COUNTRIES_CITY   values (130,'Norfolk Island','Kingston');
Insert into  TMP_COUNTRIES_CITY   values (131,'Northern Mariana Islands','Saipan');
Insert into  TMP_COUNTRIES_CITY   values (132,'Norway','Oslo');
Insert into  TMP_COUNTRIES_CITY   values (133,'Oman','Masqat');
Insert into  TMP_COUNTRIES_CITY   values (134,'Pakistan','Islamabad');
Insert into  TMP_COUNTRIES_CITY   values (135,'Palau','Koror');
Insert into  TMP_COUNTRIES_CITY   values (136,'Panama','Panama');
Insert into  TMP_COUNTRIES_CITY   values (137,'Papua New Guinea','Port Moresby');
Insert into  TMP_COUNTRIES_CITY   values (138,'Paraguay','Asuncion');
Insert into  TMP_COUNTRIES_CITY   values (139,'Peru','Lima');
Insert into  TMP_COUNTRIES_CITY   values (140,'Philippines','Manila');
Insert into  TMP_COUNTRIES_CITY   values (141,'Poland','Warsaw');
Insert into  TMP_COUNTRIES_CITY   values (142,'Portugal','Lisbon');
Insert into  TMP_COUNTRIES_CITY   values (143,'Puerto Rico','San Juan');
Insert into  TMP_COUNTRIES_CITY   values (144,'Qatar','Doha');
Insert into  TMP_COUNTRIES_CITY   values (145,'Republic of Korea','Seoul');
Insert into  TMP_COUNTRIES_CITY   values (146,'Romania','Bucuresti');
Insert into  TMP_COUNTRIES_CITY   values (147,'Russian Federation','Moskva');
Insert into  TMP_COUNTRIES_CITY   values (148,'Rwanda','Kigali');
Insert into  TMP_COUNTRIES_CITY   values (149,'Saint Kitts and Nevis','Basseterre');
Insert into  TMP_COUNTRIES_CITY   values (150,'Saint Lucia','Castries');
Insert into  TMP_COUNTRIES_CITY   values (151,'Saint Pierre and Miquelon','Saint-Pierre');
Insert into  TMP_COUNTRIES_CITY   values (152,'Saint Vincent and the Grenadines','Kingstown');
Insert into  TMP_COUNTRIES_CITY   values (153,'Samoa','Apia');
Insert into  TMP_COUNTRIES_CITY   values (154,'San Marino','San Marino');
Insert into  TMP_COUNTRIES_CITY   values (155,'Sao Tome and Principe','Sao Tome');
Insert into  TMP_COUNTRIES_CITY   values (156,'Saudi Arabia','Riyadh');
Insert into  TMP_COUNTRIES_CITY   values (157,'Senegal','Dakar');
Insert into  TMP_COUNTRIES_CITY   values (158,'Sierra Leone','Freetown');
Insert into  TMP_COUNTRIES_CITY   values (159,'Slovakia','Bratislava');
Insert into  TMP_COUNTRIES_CITY   values (160,'Slovenia','Ljubljana');
Insert into  TMP_COUNTRIES_CITY   values (161,'Solomon Islands','Honiara');
Insert into  TMP_COUNTRIES_CITY   values (162,'Somalia','Mogadishu');
Insert into  TMP_COUNTRIES_CITY   values (163,'South Africa','Pretoria');
Insert into  TMP_COUNTRIES_CITY   values (164,'Spain','Madrid');
Insert into  TMP_COUNTRIES_CITY   values (165,'Sudan','Khartoum');
Insert into  TMP_COUNTRIES_CITY   values (166,'Suriname','Paramaribo');
Insert into  TMP_COUNTRIES_CITY   values (167,'Swaziland','Mbabane (Adm.)');
Insert into  TMP_COUNTRIES_CITY   values (168,'Sweden','Stockholm');
Insert into  TMP_COUNTRIES_CITY   values (169,'Switzerland','Bern');
Insert into  TMP_COUNTRIES_CITY   values (170,'Syrian Arab Republic','Damascus');
Insert into  TMP_COUNTRIES_CITY   values (171,'Tajikistan','Dushanbe');
Insert into  TMP_COUNTRIES_CITY   values (172,'Thailand','Bangkok');
Insert into  TMP_COUNTRIES_CITY   values (173,'Togo','Lome');
Insert into  TMP_COUNTRIES_CITY   values (174,'Tonga','Nuku''alofa');
Insert into  TMP_COUNTRIES_CITY   values (175,'Tunisia','Tunis');
Insert into  TMP_COUNTRIES_CITY   values (176,'Turkey','Ankara');
Insert into  TMP_COUNTRIES_CITY   values (177,'Turkmenistan','Ashgabat');
Insert into  TMP_COUNTRIES_CITY   values (178,'Tuvalu','Funafuti');
Insert into  TMP_COUNTRIES_CITY   values (179,'Uganda','Kampala');
Insert into  TMP_COUNTRIES_CITY   values (180,'Ukraine','Kiev (Rus)');
Insert into  TMP_COUNTRIES_CITY   values (181,'United Arab Emirates','Abu Dhabi');
Insert into  TMP_COUNTRIES_CITY   values (182,'United Kingdom of Great Britain and Northern Ireland','London');
Insert into  TMP_COUNTRIES_CITY   values (183,'United Republic of Tanzania','Dodoma');
Insert into  TMP_COUNTRIES_CITY   values (184,'United States of America','Washington DC');
Insert into  TMP_COUNTRIES_CITY   values (185,'United States Virgin Islands','Charlotte Amalie');
Insert into  TMP_COUNTRIES_CITY   values (186,'Uruguay','Montevideo');
Insert into  TMP_COUNTRIES_CITY   values (187,'Uzbekistan','Tashkent');
Insert into  TMP_COUNTRIES_CITY   values (188,'Vanuatu','Port-Vila');
Insert into  TMP_COUNTRIES_CITY   values (189,'Venezuela (Bolivarian Republic of)','Caracas');
Insert into  TMP_COUNTRIES_CITY   values (190,'Viet Nam','Hanoi');
Insert into  TMP_COUNTRIES_CITY   values (191,'Zambia','Lusaka');
Insert into  TMP_COUNTRIES_CITY   values (192,'Zimbabwe','Harare');

commit;

