ALTER TABLE U_STG.LC_PROD_CATEGORIES
 DROP PRIMARY KEY CASCADE;

DROP TABLE U_STG.LC_PROD_CATEGORIES CASCADE CONSTRAINTS;

CREATE TABLE U_STG.LC_PROD_CATEGORIES
(
  PROD_CATEGORY_ID  NUMBER(20)                  NOT NULL,
  CATEGORY_CODE     VARCHAR2(15 BYTE),
  CATEGORY_DESC     VARCHAR2(70 BYTE),
  LOCALIZATION_ID   NUMBER(22)                  NOT NULL,
  INSERT_DT         DATE,
  UPDATE_DT         DATE
)
TABLESPACE TS_STG_DATA_01
;


CREATE UNIQUE INDEX U_STG.PK_LC_PROD_CATEGORIES ON U_STG.LC_PROD_CATEGORIES
(PROD_CATEGORY_ID, LOCALIZATION_ID)
LOGGING
TABLESPACE TS_STG_DATA_01
;


ALTER TABLE U_STG.LC_PROD_CATEGORIES ADD (
  CONSTRAINT PK_LC_PROD_CATEGORIES
 PRIMARY KEY
 (PROD_CATEGORY_ID, LOCALIZATION_ID)
    USING INDEX 
    TABLESPACE TS_STG_DATA_01
 );

ALTER TABLE U_STG.LC_PROD_CATEGORIES ADD (
  CONSTRAINT FK_LC_PROD__REFERENCE_T_LOCALI 
 FOREIGN KEY (LOCALIZATION_ID) 
 REFERENCES U_STG.T_LOCALIZATIONS (LOCALIZATION_ID),
  CONSTRAINT FK_LC_PROD__REFERENCE_T_PROD_C 
 FOREIGN KEY (PROD_CATEGORY_ID) 
 REFERENCES U_STG.T_PROD_CATEGORY (PROD_CATEGORY_ID));

GRANT INSERT, SELECT, UPDATE ON U_STG.LC_PROD_CATEGORIES TO U_DW_EXT_REFERENCES;
