ALTER TABLE U_STG.T_PROD_CATEGORY
 DROP PRIMARY KEY CASCADE;

DROP TABLE U_STG.T_PROD_CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE U_STG.T_PROD_CATEGORY
(
  PROD_CATEGORY_ID  NUMBER(20)                  NOT NULL,
  CATEGORY_CODE     VARCHAR2(15 BYTE),
  INSERT_DT         DATE,
  UPDATE_DT         DATE
)
TABLESPACE TS_STG_DATA_01
;


CREATE UNIQUE INDEX U_STG.PK_T_PROD_CATEGORY ON U_STG.T_PROD_CATEGORY
(PROD_CATEGORY_ID)
LOGGING
TABLESPACE TS_STG_DATA_01;


ALTER TABLE U_STG.T_PROD_CATEGORY ADD (
  CONSTRAINT PK_T_PROD_CATEGORY
 PRIMARY KEY
 (PROD_CATEGORY_ID)
    USING INDEX 
    TABLESPACE TS_STG_DATA_01
  );

GRANT INSERT, SELECT, UPDATE ON U_STG.T_PROD_CATEGORY TO U_DW_EXT_REFERENCES;
