--ALTER TABLE CONTRACTS
--   DROP CONSTRAINT FK_CONTRACT_REFERENCE_CARS;
--
--ALTER TABLE CONTRACTS
--   DROP CONSTRAINT FK_CONTRACT_REFERENCE_EMPLOYEE;
--
--ALTER TABLE CONTRACTS
--   DROP CONSTRAINT FK_CONTRACT_REFERENCE_CUSTOMER;

DROP TABLE CONTRACTS CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: "CONTRACTS"                                           */
/*==============================================================*/
CREATE TABLE CONTRACTS 
(
CONTRACT_ID        NUMBER(20)           NOT NULL,
   EVENT_DT           DATE,
   CONTRACT_NUMBER    VARCHAR2(50 CHAR),
   CAR_ID             NUMBER(20),
   EMP_ID         NUMBER(20),
   CUST_ID        NUMBER(20),
   PRICE              NUMBER(20),
   CONSTRAINT PK_CONTRACTS PRIMARY KEY (CONTRACT_ID)
);

ALTER TABLE CONTRACTS
   ADD CONSTRAINT FK_CONTRACT_REFERENCE_CARS FOREIGN KEY (CAR_ID)
      REFERENCES CARS (CAR_ID);

ALTER TABLE CONTRACTS
   ADD CONSTRAINT FK_CONTRACT_REFERENCE_EMPLOYEE FOREIGN KEY (EMP_ID)
      REFERENCES EMPLOYEES (EMP_ID);

ALTER TABLE CONTRACTS
   ADD CONSTRAINT FK_CONTRACT_REFERENCE_CUSTOMER FOREIGN KEY (CUST_ID)
      REFERENCES CUSTOMERS (CUST_ID);



GRANT DELETE,INSERT,UPDATE,SELECT ON CONTRACTS TO u_dw_cleansing;


SELECT * FROM contracts;