/*CREATE TABLES FOR DW*/

-- DROP TABLE T_DW_OPERATION_TYPES_METHODS
-- DROP TABLE T_DW_OPERATION_TYPES
-- DROP TABLE T_DW_CURRENCY_SCD
-- DROP TABLE T_DW_USERS 
-- DROP TABLE T_DW_FCT


CREATE TABLE T_DW_OPERATION_TYPES_METHODS
(
   OPERATION_TYPE_METHOD_ID     NUMBER (32),
   OPERATION_TYPE_METHOD_DESC   VARCHAR (32)
);

CREATE TABLE T_DW_OPERATION_TYPES
(
   OPERATION_TYPE_ID           NUMBER (32),
   OPERATION_TYPE_DESC         VARCHAR2 (32),
   OPERATION_TYPE_MAX_AMOUNT   NUMBER (32),
   OPERATION_TYPE_MIN_AMOUNT   NUMBER (32)
);


CREATE TABLE T_DW_CURRENCY_SCD
(
   CURRENCY_SUR_ID      NUMBER(32),
   CURRENCY_ID          NUMBER(32),
   CURRENCY_TYPE_ID     NUMBER(10),
   CURRENCY_DESC        VARCHAR2(32),
   ACTUAL               VARCHAR2(5),
   BEGIN_EVENT          DATE,
   END_EVENT            DATE
);


INSERT INTO T_DW_CURRENCY_SCD (CURRENCY_SUR_ID, CURRENCY_ID, CURRENCY_TYPE_ID, CURRENCY_DESC, ACTUAL, BEGIN_EVENT, END_EVENT) VALUES (1,1,0,'EURO','N', ADD_MONTHS(TRUNC(SYSDATE), -999),TRUNC (SYSDATE-1));
INSERT INTO T_DW_CURRENCY_SCD (CURRENCY_SUR_ID, CURRENCY_ID, CURRENCY_TYPE_ID, CURRENCY_DESC, ACTUAL, BEGIN_EVENT, END_EVENT) VALUES (2,1,1,'EURO','Y', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), +999));
INSERT INTO T_DW_CURRENCY_SCD (CURRENCY_SUR_ID, CURRENCY_ID, CURRENCY_TYPE_ID, CURRENCY_DESC, ACTUAL, BEGIN_EVENT, END_EVENT) VALUES (3,2,1,'DOLLAR','Y',ADD_MONTHS(TRUNC(SYSDATE), -3),TRUNC (SYSDATE));
INSERT INTO T_DW_CURRENCY_SCD (CURRENCY_SUR_ID, CURRENCY_ID, CURRENCY_TYPE_ID, CURRENCY_DESC, ACTUAL, BEGIN_EVENT, END_EVENT) VALUES (4,3,1,'POUND','Y', ADD_MONTHS(TRUNC(SYSDATE), -3),TRUNC (SYSDATE));
INSERT INTO T_DW_CURRENCY_SCD (CURRENCY_SUR_ID, CURRENCY_ID, CURRENCY_TYPE_ID, CURRENCY_DESC, ACTUAL, BEGIN_EVENT, END_EVENT) VALUES (5,4,0,'KRONA','Y', ADD_MONTHS(TRUNC(SYSDATE), -3),TRUNC (SYSDATE));
INSERT INTO T_DW_CURRENCY_SCD (CURRENCY_SUR_ID, CURRENCY_ID, CURRENCY_TYPE_ID, CURRENCY_DESC, ACTUAL, BEGIN_EVENT, END_EVENT) VALUES (6,5,1,'FRANC','Y', ADD_MONTHS(TRUNC(SYSDATE), -3),TRUNC (SYSDATE));
INSERT INTO T_DW_CURRENCY_SCD (CURRENCY_SUR_ID, CURRENCY_ID, CURRENCY_TYPE_ID, CURRENCY_DESC, ACTUAL, BEGIN_EVENT, END_EVENT) VALUES (7,6,1,'YEN','Y', ADD_MONTHS(TRUNC(SYSDATE), -3),TRUNC (SYSDATE));
INSERT INTO T_DW_CURRENCY_SCD (CURRENCY_SUR_ID, CURRENCY_ID, CURRENCY_TYPE_ID, CURRENCY_DESC, ACTUAL, BEGIN_EVENT, END_EVENT) VALUES (8,7,0,'KRONER','Y', ADD_MONTHS(TRUNC(SYSDATE), -3),TRUNC (SYSDATE));
INSERT INTO T_DW_CURRENCY_SCD (CURRENCY_SUR_ID, CURRENCY_ID, CURRENCY_TYPE_ID, CURRENCY_DESC, ACTUAL, BEGIN_EVENT, END_EVENT) VALUES (9,8,0,'RUBL','Y', ADD_MONTHS(TRUNC(SYSDATE), -3),TRUNC (SYSDATE));

CREATE TABLE T_DW_USERS 
(
   User_ID         NUMBER DEFAULT NULL,
   First_Name      VARCHAR2 (255) DEFAULT NULL,
   Last_Name       VARCHAR2 (255) DEFAULT NULL,
   Gender          VARCHAR2 (255) DEFAULT NULL,
   Year_Of_Birth   VARCHAR2 (100) DEFAULT NULL,
   User_Balance    VARCHAR2 (50) DEFAULT NULL,
   Country_ID      NUMBER (32) DEFAULT NULL,
   Marige_Status   VARCHAR2 (255) DEFAULT NULL
);

CREATE TABLE T_DW_FCT
(
   TRANSACTION_ID             NUMBER,
   OPERATION_TYPE_ID          NUMBER,
   OPERATION_TYPE_METHOD_ID   NUMBER,
   COUNTRY_ID                 NUMBER,
   USER_ID                    NUMBER (32),
   EVENT_DT                   DATE,
   CURRENCY_ID                NUMBER (32),
   FCT_AMOUNT                 NUMBER (32)
);
