grant select on U_DW_REFERENCES.T_ACTIONS to U_DW_EXT_REFERENCES;
grant insert on U_DW_REFERENCES.T_ACTIONS to U_DW_EXT_REFERENCES;
grant update on U_DW_REFERENCES.T_ACTIONS to U_DW_EXT_REFERENCES;
grant delete on U_DW_REFERENCES.T_ACTIONS to U_DW_EXT_REFERENCES;

grant select on U_DW_REFERENCES.VIEW_DIM_GEO_COUNTRY to U_DW;