drop SEQUENCE SEQ_T_RESTAURANT_TYPES;

CREATE SEQUENCE SEQ_T_RESTAURANT_TYPES
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
 drop SEQUENCE SEQ_T_RESTAURANTS;

CREATE SEQUENCE SEQ_T_RESTAURANTS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;