--SA_FINANCE
CREATE TABLESPACE ts_sa_finance_data_01
DATAFILE 'FINANCE_SOURCES.DAT'
SIZE 100M
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO
 LOGGING
 
 --DW_CL
CREATE TABLESPACE ts_dw_cl
DATAFILE 'FINANCE_SOURCES1.DAT'
SIZE 200M
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO
 NOLOGGING

--DW
CREATE TABLESPACE ts_dw_data_01
DATAFILE 'FINANCE_SOURCES2.DAT'
SIZE 300M
 AUTOEXTEND ON NEXT 100M
 SEGMENT SPACE MANAGEMENT AUTO
 LOGGING

--SAL_DW_CL
CREATE TABLESPACE  ts_sal_dw_cl
DATAFILE 'FINANCE_SOURCES3.DAT'
SIZE 100M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO
NOLOGGING

--SAL_CL
CREATE TABLESPACE  ts_sal_sl
DATAFILE 'FINANCE_SOURCES4.DAT'
SIZE 100M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO
NOLOGGING

--SAL
CREATE TABLESPACE  ts_sal_data_01
DATAFILE 'FINANCE_SOURCES5.DAT'
SIZE 100M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO
LOGGING