GRANT CREATE MATERIALIZED VIEW TO u_dw;
GRANT CREATE VIEW TO u_dw;
GRANT CREATE ANY TABLE TO u_dw;
GRANT ON COMMIT REFRESH TO u_dw;
GRANT SELECT ON u_sa_data.contracts TO u_dw WITH GRANT OPTION;
GRANT COMMENT ANY TABLE TO u_dw;