CREATE TABLESPACE ts_sb_m
DATAFILE 'db_qpt_sb_m.dat'
SIZE 150M
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;



CREATE USER sb_mbackup
IDENTIFIED BY "123456"
DEFAULT TABLESPACE ts_sb_m;

GRANT CONNECT,RESOURCE TO sb_mbackup;
GRANT SELECT ANY TABLE TO sb_mbackup;