CREATE TABLESPACE ts_SB_MBackUp
DATAFILE 'SB_MBackUp_data_01.dat'
SIZE 50M
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;
 
 CREATE USER SB_MBackUp 
  IDENTIFIED BY "123456"
    DEFAULT TABLESPACE ts_SB_MBackUp;

GRANT CONNECT,RESOURCE TO SB_MBackUp;
