DROP TABLE ext_prod_sorts;

CREATE TABLE ext_prod_sorts ( sort_name VARCHAR2 ( 70 CHAR ) )
ORGANIZATION EXTERNAL
                       ( TYPE oracle_loader DEFAULT DIRECTORY ext_references
 ACCESS PARAMETERS ( RECORDS DELIMITED BY NEWLINE NOBADFILE NODISCARDFILE NOLOGFILE FIELDS
 MISSING FIELD VALUES ARE NULL(  sort_name CHAR ( 70 ) )  )
 LOCATION ('beer_sorts.csv'))REJECT LIMIT UNLIMITED;