begin
pkg_load_sal_star.load_dim_payment_systems;
u_dw_references.load_dim_geo_countries;
pkg_load_sal_star.load_dim_delivery_systems;
pkg_load_sal_star.load_dim_times;
pkg_load_sal_star.load_dim_products;
pkg_load_sal_star.load_fct_sales_dd;
end;