DROP USER U_SAL CASCADE;
CREATE USER "U_SAL"
  IDENTIFIED BY "12345678"
    DEFAULT TABLESPACE ts_star_01;


GRANT CONNECT,CREATE VIEW,RESOURCE TO "U_SAL";

ALTER USER U_SAL QUOTA UNLIMITED ON ts_star_01;
ALTER USER U_SAL QUOTA UNLIMITED ON ts_fct_arch;
ALTER USER U_SAL QUOTA UNLIMITED ON ts_fct_2013;

/