/*CREATE TABLES FOR SAL*/

-- DROP TABLE DIM_OPERATION_TYPES_METHODS
-- DROP TABLE DIM_OPERATION_TYPES
-- DROP TABLE DIM_CURRENCY_SCD
-- DROP TABLE DIM_USERS 
-- DROP TABLE FCT_TRANSACTIONS


-- SELECT * FROM U_STR_DATA.DIM_OPERATION_TYPES_METHODS
-- SELECT * FROM U_STR_DATA.DIM_OPERATION_TYPES
-- SELECT * FROM U_STR_DATA.DIM_CURRENCY_SCD
-- SELECT * FROM U_STR_DATA.DIM_USERS 


CREATE TABLE DIM_OPERATION_TYPES_METHODS
(
   OPERATION_TYPE_METHOD_ID     NUMBER (32),
   OPERATION_TYPE_METHOD_DESC   VARCHAR (32)
);

CREATE TABLE DIM_OPERATION_TYPES
(
   OPERATION_TYPE_ID           NUMBER (32),
   OPERATION_TYPE_DESC         VARCHAR2 (32),
   OPERATION_TYPE_MAX_AMOUNT   NUMBER (32),
   OPERATION_TYPE_MIN_AMOUNT   NUMBER (32)
);


CREATE TABLE DIM_CURRENCY_SCD
(
   CURRENCY_SUR_ID      NUMBER(32),
   CURRENCY_ID          NUMBER(32),
   CURRENCY_TYPE_ID     NUMBER(10),
   CURRENCY_DESC        VARCHAR2(32),
   ACTUAL               VARCHAR2(5),
   BEGIN_EVENT          DATE,
   END_EVENT            DATE
);


CREATE TABLE DIM_USERS 
(
   User_ID         NUMBER DEFAULT NULL,
   First_Name      VARCHAR2 (255) DEFAULT NULL,
   Last_Name       VARCHAR2 (255) DEFAULT NULL,
   Gender          VARCHAR2 (255) DEFAULT NULL,
   Year_Of_Birth   VARCHAR2 (100) DEFAULT NULL,
   User_Balance    VARCHAR2 (50) DEFAULT NULL

);

CREATE TABLE DIM_GEN_TIMES
AS
SELECT * FROM U_SAL_CL.DIM_GEN_TIMES

CREATE TABLE DIM_GEO
AS
SELECT * FROM U_SAL_CL.DIM_GEO
