/* Formatted on 8/4/2013 12:51:03 PM (QP5 v5.139.911.3011) */
CREATE TABLESPACE st_data DATAFILE 'ST_DATA_01.dbf' SIZE 100 M AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE USER st IDENTIFIED BY pass DEFAULT TABLESPACE st_data QUOTA UNLIMITED ON st_data;

GRANT CONNECT, RESOURCE TO st;

GRANT CREATE VIEW TO st;

CREATE TABLESPACE cls_st_data DATAFILE 'CLS_ST_DATA_01.dbf' SIZE 10 M AUTOEXTEND ON NEXT 1 M MAXSIZE 20M;

CREATE USER cls_st IDENTIFIED BY pass DEFAULT TABLESPACE cls_st_data QUOTA UNLIMITED ON cls_st_data;

GRANT CONNECT, RESOURCE TO cls_st;

GRANT CREATE VIEW TO st_cls;