ALTER SYSTEM SET db_create_file_dest = '/oracle/oradata/$ORACLE_UNQNAME';

CREATE TABLESPACE ts_sa_data_01
DATAFILE 'db_qpt_sa_data_01.dat'
SIZE 200M
 AUTOEXTEND ON NEXT 50M
NOLOGGING
DEFAULT NOCOMPRESS
SEGMENT SPACE MANAGEMENT AUTO;