DROP TABLE U_CLS_STAR.CLS_FCT_MONTHLY CASCADE CONSTRAINTS;

CREATE TABLE U_CLS_STAR.CLS_FCT_MONTHLY
(
  EVENT_DT     DATE,
  PRODUCT_ID   NUMBER(20),
  ORD_GEO_ID   NUMBER(22),
  CUSTOMER_ID  NUMBER(20),
  QUANTITY     NUMBER(10),
  TOTAL_COST   NUMBER(25,2),
  AMOUNT_SOLD  NUMBER(25,2)
)
TABLESPACE TS_FCT_2013
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT SELECT ON U_CLS_STAR.CLS_FCT_MONTHLY TO U_SAL;
