DROP TABLE U_CLS_STAR.CLS_DIM_CUSTOMERS CASCADE CONSTRAINTS;

CREATE TABLE U_CLS_STAR.CLS_DIM_CUSTOMERS
(
  CUSTOMER_ID   NUMBER(20)                      NOT NULL,
  CUST_DESC     VARCHAR2(70 BYTE),
  STATUS_DESC   VARCHAR2(70 BYTE),
  COUNTRY_DESC  VARCHAR2(200 CHAR)              NOT NULL
)
TABLESPACE TS_CLS_STAR_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
