DROP TABLE U_CLS_STAR.CLS_FCT_MONTHLY CASCADE CONSTRAINTS;

CREATE TABLE U_CLS_STAR.CLS_FCT_MONTHLY
(
  EVENT_DT     DATE,
  PRODUCT_ID   NUMBER(20),
  ORD_GEO_ID   NUMBER(22),
  CUSTOMER_ID  NUMBER(20),
  QUANTITY     NUMBER,
  AMOUNT_SOLD  NUMBER
)
TABLESPACE TS_CLS_FCT_MONTHLY
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
