/*LOAD DATA FROM DW_CL TO DW*/

CREATE OR REPLACE PACKAGE PKG_FROM_CL_TO_DW
AS
   PROCEDURE LOAD_TO_DW_USERS;
   PROCEDURE LOAD_TO_DW_FCT;
   PROCEDURE LOAD_TO_DW_OPER_TYPE_METHOD;
   PROCEDURE LOAD_TO_DW_OPER_TYPE;
END;