/* RUN PACKAGE TO LAD DATA FROM CL TO DW */
--Alter Session Enable Parallel DML;

BEGIN
   PKG_FROM_CL_TO_DW.LOAD_TO_DW_USERS;
   PKG_FROM_CL_TO_DW.LOAD_TO_DW_FCT;
   PKG_FROM_CL_TO_DW.LOAD_TO_DW_OPER_TYPE_METHOD;
  END;