ALTER TABLE U_STG.T_CUST_STATUS
 DROP PRIMARY KEY CASCADE;

DROP TABLE U_STG.T_CUST_STATUS CASCADE CONSTRAINTS;

CREATE TABLE U_STG.T_CUST_STATUS
(
  STATUS_ID    NUMBER(20)                       NOT NULL,
  STATUS_CODE  VARCHAR2(20 BYTE),
  INSERT_DT    DATE,
  UPDATE_DT    DATE
)
TABLESPACE TS_STG_DATA_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX U_STG.PK_T_CUST_STATUS ON U_STG.T_CUST_STATUS
(STATUS_ID)
LOGGING
TABLESPACE TS_STG_DATA_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE U_STG.T_CUST_STATUS ADD (
  CONSTRAINT PK_T_CUST_STATUS
 PRIMARY KEY
 (STATUS_ID)
    USING INDEX 
    TABLESPACE TS_STG_DATA_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          160K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT INSERT, SELECT, UPDATE ON U_STG.T_CUST_STATUS TO U_DW_EXT_REFERENCES;
