DROP MATERIALIZED VIEW LOG ON u_dw_ext_references.cls_operations;
DROP MATERIALIZED VIEW LOG ON u_dw_ext_references.cls_restaurants;
DROP MATERIALIZED VIEW LOG ON u_dw_ext_references.cls_dishes;
 
 
CREATE MATERIALIZED VIEW LOG ON u_dw_ext_references.cls_operations
WITH rowid, SEQUENCE (EVENT_DT, TRANSACTION_CODE, RESTAURANT_CODE, DISH_CODE, UNIT_PRICE_DOL, UNIT_AMOUNT, TOTAL_PRICE_DOL)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON u_dw_ext_references.cls_restaurants
WITH rowid, SEQUENCE (RESTAURANT_CODE)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON u_dw_ext_references.cls_dishes
WITH rowid,  SEQUENCE (DISH_CODE)
INCLUDING NEW VALUES;