/*LOAD DATA FROM DW TO SAL_CL*/

CREATE OR REPLACE PACKAGE PKG_FROM_DW_TO_SAL_CL
AS
   PROCEDURE LOAD_TO_SAL_CL_USERS;
   PROCEDURE LOAD_TO_SAL_CL_TRANSACTIONS;
   PROCEDURE LOAD_TO_SAL_CL_OPER_TYPE_MET;
   PROCEDURE LOAD_TO_SAL_CL_OPER_TYPE;
   PROCEDURE LOAD_TO_SAL_CL_CURRENCY;
END;