/* RUN PACKAGE TO LAD DATA FROM DW TO SAL_CL */
--Alter Session Enable Parallel DML;

BEGIN
  PKG_FROM_DW_TO_SAL_CL.LOAD_TO_SAL_CL_USERS;
  PKG_FROM_DW_TO_SAL_CL.LOAD_TO_SAL_CL_TRANSACTIONS;
  PKG_FROM_DW_TO_SAL_CL.LOAD_TO_SAL_CL_OPER_TYPE_MET;
  PKG_FROM_DW_TO_SAL_CL.LOAD_TO_SAL_CL_OPER_TYPE;
  PKG_FROM_DW_TO_SAL_CL.LOAD_TO_SAL_CL_CURRENCY;
   
END;