DROP TABLE U_DW_REFERENCES.DIM_GEO_SCD CASCADE CONSTRAINTS;

CREATE TABLE U_DW_REFERENCES.DIM_GEO_SCD
(  GEO_SUR_ID         NUMBER(10)                 DEFAULT "U_DW_REFERENCES"."SCD_SEQ"."NEXTVAL",
  GEO_ID             NUMBER(5),
  COUNTRY_ID         NUMBER(22),
  COUNTRY_DESC       VARCHAR2(200 CHAR),
  COUNTRY_CODE_A3    VARCHAR2(30 CHAR),
  REGION_GEO_ID      NUMBER,
  REGION_CODE        VARCHAR2(30 CHAR),
  REGION_DESC        VARCHAR2(200 CHAR),
  PART_GEO_ID        NUMBER,
  PART_ID            NUMBER,
  PART_CODE          VARCHAR2(30 CHAR),
  PART_DESC          VARCHAR2(200 CHAR),
  GEO_SYSTEM_GEO_ID  NUMBER,
  GEO_SYSTEM_CODE    VARCHAR2(30 CHAR),
  GEO_SYSTEM_DESC    VARCHAR2(200 CHAR),
  VALID_FROM         DATE,
  VALID_TO           DATE,
  IS_VALID           NUMBER(1)                  DEFAULT 1,
  LEVEL_CODE         NUMBER(3)

)
TABLESPACE TS_REFERENCES_DATA_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
