CREATE TABLE T_MONTHS AS (
  SELECT DISTINCT
  TRUNC(( SD + RN ),'MM') MONTH_ID,
  TO_CHAR( SD + RN, 'MM' ) CALENDAR_MONTH_NUMBER,
  TO_CHAR( LAST_DAY( SD + RN ), 'DD' ) DAYS_IN_CAL_MONTH,
  LAST_DAY( SD + RN ) END_OF_CAL_MONTH,
  TO_CHAR( SD + RN, 'FMMONTH' ) CALENDAR_MONTH_NAME,
  TRUNC(( SD + RN ), 'Q') QUARTER_ID,
  TRUNC(( SD + RN ), 'YYYY') YEAR_ID
 FROM
  ( SELECT 
      TO_DATE( '12/31/1999', 'MM/DD/YYYY' ) SD,
      ROWNUM RN
    FROM DUAL
      CONNECT BY LEVEL <= 7300
  ));
  
ALTER TABLE T_MONTHS
ADD CONSTRAINT TM_PK PRIMARY KEY (MONTH_ID);

ALTER TABLE T_MONTHS
ADD CONSTRAINT TM_FK1 FOREIGN KEY (QUARTER_ID) REFERENCES T_QUARTERS (QUARTER_ID);

ALTER TABLE T_MONTHS
ADD CONSTRAINT TM_FK2 FOREIGN KEY (YEAR_ID) REFERENCES T_YEARS (YEAR_ID);
