CREATE TABLE T_YEARS AS (
SELECT DISTINCT
  TRUNC(( SD + RN ), 'YYYY') YEAR_ID,
 TO_CHAR( SD + RN, 'YYYY' ) CALENDAR_YEAR,
  ( TO_DATE( '12/31/' || TO_CHAR( SD + RN, 'YYYY' ), 'MM/DD/YYYY' )
    - TRUNC( SD + RN, 'YEAR' ) ) DAYS_IN_CAL_YEAR,
  TRUNC( SD + RN, 'YEAR' ) BEG_OF_CAL_YEAR,
  TO_DATE( '12/31/' || TO_CHAR( SD + RN, 'YYYY' ), 'MM/DD/YYYY' ) END_OF_CAL_YEAR
FROM
  ( 
    SELECT 
      TO_DATE( '12/20/1999', 'MM/DD/YYYY' ) SD,
      ROWNUM RN
    FROM DUAL
      CONNECT BY LEVEL <= 7311
  ));
  

ALTER TABLE T_YEARS
ADD CONSTRAINT  TY_PK PRIMARY KEY (YEAR_ID);
