ALTER TABLE CONTRACTS
   DROP CONSTRAINT FK_CONTRACT_REFERENCE_CUSTOMER;

ALTER TABLE CUSTOMERS
   DROP CONSTRAINT FK_CUSTOMER_REFERENCE_CITIES;

DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: CUSTOMERS                                          */
/*==============================================================*/
CREATE TABLE CUSTOMERS 
(
   CUST_ID            NUMBER(20)           NOT NULL,
   CUST_CODE          NUMBER(20),
   PASSPORT_NUMBER    VARCHAR2(50 CHAR),
   FIRST_NAME         VARCHAR2(50 CHAR),
   LAST_NAME          VARCHAR2(50),
   CITY_ID            NUMBER(20),
   ADRESS             VARCHAR2(50 CHAR),
   GENDER             VARCHAR2(10 CHAR),
   INSERT_DT          DATE,
   UPDATE_DT          DATE,
   CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUST_ID)
);

ALTER TABLE CUSTOMERS
   ADD CONSTRAINT FK_CUSTOMER_REFERENCE_CITIES FOREIGN KEY (CITY_ID)
      REFERENCES CITIES (CITY_ID);


GRANT DELETE,INSERT,UPDATE,SELECT ON CUSTOMERS TO u_dw_cleansing;



SELECT * FROM CUSTOMERS;
SELECT * FROM CITIES;