DROP TABLE U_SAL.DIM_GEO CASCADE CONSTRAINTS;

CREATE TABLE U_SAL.DIM_GEO
(
  COUNTRY_GEO_ID   NUMBER(22),
  COUNTRY_ID       NUMBER(22),
  COUNTRY_CODE_A3  VARCHAR2(30 CHAR),
  COUNTRY_DESC     VARCHAR2(200 CHAR),
  REGION_GEO_ID    NUMBER,
  REGION_ID        NUMBER,
  REGION_DESC      VARCHAR2(200 CHAR),
  PART_GEO_ID      NUMBER,
  PART_ID          NUMBER,
  PART_DESC        VARCHAR2(200 CHAR),
  VALID_FROM       VARCHAR2(9 BYTE),
  VALID_TO         VARCHAR2(9 BYTE),
  IS_ACTUAL        CHAR(1 BYTE),
  SURR_ID          NUMBER(25)
)
TABLESPACE TS_STAR_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT ALTER, INSERT, SELECT ON U_SAL.DIM_GEO TO U_CLS_STAR;
