DROP TABLE U_SAL.DIM_TIMES CASCADE CONSTRAINTS;

CREATE TABLE U_SAL.DIM_TIMES
(
  TIME_ID                  DATE,
  DAY_NAME                 VARCHAR2(9 BYTE),
  DAY_NUMBER_IN_WEEK       VARCHAR2(1 BYTE),
  DAY_NUMBER_IN_MONTH      VARCHAR2(2 BYTE),
  DAY_NUMBER_IN_YEAR       VARCHAR2(3 BYTE),
  CALENDAR_WEEK_NUMBER     VARCHAR2(1 BYTE),
  WEEK_ENDING_DATE         DATE,
  CALENDAR_MONTH_NUMBER    VARCHAR2(2 BYTE),
  DAYS_IN_CAL_MONTH        VARCHAR2(2 BYTE),
  END_OF_CAL_MONTH         DATE,
  CALENDAR_MONTH_NAME      VARCHAR2(9 BYTE),
  DAYS_IN_CAL_QUARTER      NUMBER,
  BEG_OF_CAL_QUARTER       DATE,
  END_OF_CAL_QUARTER       DATE,
  CALENDAR_QUARTER_NUMBER  VARCHAR2(1 BYTE),
  CALENDAR_YEAR            VARCHAR2(4 BYTE),
  DAYS_IN_CAL_YEAR         NUMBER,
  BEG_OF_CAL_YEAR          DATE,
  END_OF_CAL_YEAR          DATE
)
TABLESPACE TS_STAR_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
