DROP TABLE U_SAL.FCT_INCOME_PRODUCTS_DAILY CASCADE CONSTRAINTS;

CREATE TABLE U_SAL.FCT_INCOME_PRODUCTS_DAILY
(
  EVENT_DT     DATE,
  PRODUCT_ID   NUMBER(20),
  ORD_GEO_ID   NUMBER(22),
  CUSTOMER_ID  NUMBER(20),
  QUANTITY     NUMBER,
  AMOUNT_SOLD  NUMBER
)
TABLESPACE TS_STAR_01
PARTITION BY RANGE (event_dt)
   ( PARTITION arch
        VALUES LESS THAN
           (TO_DATE ( ' 2013-01-01 00:00:00'
                    , 'SYYYY-MM-DD HH24:MI:SS'
                    , 'NLS_CALENDAR=GREGORIAN' ))
        TABLESPACE ts_fct_arch
   , PARTITION y2013
        VALUES LESS THAN
           (TO_DATE ( ' 2014-01-01 00:00:00'
                    , 'SYYYY-MM-DD HH24:MI:SS'
                    , 'NLS_CALENDAR=GREGORIAN' ))
        TABLESPACE ts_fct_2013
  )
PARALLEL
;
