--drop trigger dw.bi_t_geo_parts
--/

--alter table dw.lc_geo_parts
 --  drop constraint FK_LC_CONTINENTS
--/

--alter table dw.t_geo_parts
--   drop constraint FK_T_GEO_OBJECTS2PARTS
--/

--drop table dw.t_geo_parts cascade constraints
--/
--
--==============================================================
-- Table: t_geo_parts                                           
--==============================================================
create table dw.t_geo_parts 
(
   geo_id               NUMBER(22,0)         not null,
   part_id              NUMBER(22,0)         not null,
   constraint PK_T_GEO_PARTS primary key (geo_id)
)
/

comment on table dw.t_geo_parts is
'Referense store: Geographical Parts of Worlds'
/

comment on column dw.t_geo_parts.geo_id is
'Unique ID for All Geography objects'
/

comment on column dw.t_geo_parts.part_id is
'ID Code of Geographical Part of World'
/

alter table dw.t_geo_parts
   add constraint FK_T_GEO_OBJECTS2PARTS foreign key (geo_id)
      references dw.t_geo_objects (geo_id)
      on delete cascade
      deferrable
/


create trigger dw.bi_t_geo_parts before insert
on dw.t_geo_parts for each row
declare
    integrity_error  exception;
    errno            integer;
    errmsg           char(200);
    lc_geo_id      NUMBER := 0;
BEGIN
   IF :new.geo_id IS NOT NULL THEN
      raise_application_error ( -20000
                              , 'Geo_id have to be ''NULL''. New Values will be generated by triger.' );
   END IF;

   INSERT INTO w_geo_objects ( geo_id
                             , geo_type_id
                             , geo_code_id )
        VALUES ( sq_geo_t_id.NEXTVAL
               , 10 --Part of World
               , :new.part_id )
     RETURNING geo_id
          INTO :new.geo_id;
--  Errors handling
exception
    when integrity_error then
       raise_application_error(errno, errmsg);
end;
/
  