
CREATE TABLESPACE "TS_STAGE_DATA_01"
DATAFILE 'db_qpt_stage_data_01.dat'
SIZE 200M
 AUTOEXTEND ON NEXT 100M
/

CREATE TABLESPACE "TS_STAGE_IDX_01"
DATAFILE 'db_qpt_stage_idx_01.dat'
SIZE 50M
 AUTOEXTEND ON NEXT 25M
/

CREATE TABLESPACE "TS_STAGE_TEMP_01"
DATAFILE 'db_qpt_stage_temp_01.dat'
SIZE 50M
 AUTOEXTEND ON NEXT 25M
/
