ALTER TABLE U_STG.LC_PRODUCTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE U_STG.LC_PRODUCTS CASCADE CONSTRAINTS;

CREATE TABLE U_STG.LC_PRODUCTS
(
  PRODUCT_ID           NUMBER(20)               NOT NULL,
  PRODUCT_NAME         VARCHAR2(70 BYTE),
  PRODUCT_CODE         VARCHAR2(15 BYTE),
  T_L_LOCALIZATION_ID  NUMBER(22)               NOT NULL,
  INSERT_DT            DATE,
  UPDATE_DT            DATE
)
TABLESPACE TS_STG_DATA_01
;


CREATE UNIQUE INDEX U_STG.PK_LC_PRODUCTS ON U_STG.LC_PRODUCTS
(PRODUCT_ID, T_L_LOCALIZATION_ID)
LOGGING
TABLESPACE TS_STG_DATA_01
;


ALTER TABLE U_STG.LC_PRODUCTS ADD (
  CONSTRAINT PK_LC_PRODUCTS
 PRIMARY KEY
 (PRODUCT_ID, T_L_LOCALIZATION_ID)
    USING INDEX 
    TABLESPACE TS_STG_DATA_01
    );

ALTER TABLE U_STG.LC_PRODUCTS ADD (
  CONSTRAINT FK_LC_PRODU_REFERENCE_T_LOCALI 
 FOREIGN KEY (T_L_LOCALIZATION_ID) 
 REFERENCES U_STG.T_LOCALIZATIONS (LOCALIZATION_ID),
  CONSTRAINT FK_LC_PRODU_REFERENCE_T_PRODUC 
 FOREIGN KEY (PRODUCT_ID) 
 REFERENCES U_STG.T_PRODUCTS (PRODUCT_ID));

GRANT INSERT, SELECT, UPDATE ON U_STG.LC_PRODUCTS TO U_DW_EXT_REFERENCES;
