CREATE TABLESPACE ts_sb_m_01
DATAFILE 'ts_sb_m_01.dat'
SIZE 200M
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;




CREATE TABLESPACE ts_sa_data_01
DATAFILE 'ts_sa_data_01.dat'
SIZE 200M
 AUTOEXTEND ON NEXT 50M
NOLOGGING
DEFAULT NOCOMPRESS
SEGMENT SPACE MANAGEMENT AUTO;



CREATE TABLESPACE ts_references_data_01
DATAFILE 'ts_references_data_01.dat'
SIZE 200M
 AUTOEXTEND ON NEXT 50M
NOLOGGING
DEFAULT NOCOMPRESS
SEGMENT SPACE MANAGEMENT AUTO;