DROP TABLE U_DW.DIM_GEO_LOCATIONS_SCD CASCADE CONSTRAINTS;

CREATE TABLE U_DW.DIM_GEO_LOCATIONS_SCD
(
  SURR_ID            NUMBER(22),
  COUNTRY_GEO_ID     NUMBER(22),
  COUNTRY_ID         NUMBER(22),
  COUNTRY_CODE_A2    VARCHAR2(30 CHAR),
  COUNTRY_CODE_A3    VARCHAR2(30 CHAR),
  COUNTRY_DESC       VARCHAR2(200 CHAR),
  REGION_GEO_ID      NUMBER(22),
  REGION_ID          NUMBER(22),
  REGION_CODE        VARCHAR2(30 CHAR),
  REGION_DESC        VARCHAR2(200 CHAR),
  PART_GEO_ID        NUMBER(22),
  PART_ID            NUMBER(22),
  PART_CODE          VARCHAR2(30 CHAR),
  PART_DESC          VARCHAR2(200 CHAR),
  GEO_SYSTEM_GEO_ID  NUMBER(22),
  GEO_SYSTEM_ID      NUMBER(22),
  GEO_SYSTEM_CODE    VARCHAR2(30 CHAR),
  GEO_SYSTEM_DESC    VARCHAR2(200 CHAR),
  FROM_DT            DATE,
  TO_DT              DATE,
  STATUS             VARCHAR2(15 BYTE)
)
TABLESPACE TS_DW;
