ALTER TABLE EMPLOYEES_ACTIONS
   DROP CONSTRAINT FK_EMPLOYEE_REFERENCE_ACTION_T;

ALTER TABLE EMPLOYEES_ACTIONS
   DROP CONSTRAINT FK_EMPLOYEE_REFERENCE_EMPLOYEE;

DROP TABLE EMPLOYEES_ACTIONS CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: "EMPLOYEES_ACTIONS"                                   */
/*==============================================================*/
CREATE TABLE EMPLOYEES_ACTIONS
(
   EMP_ID             NUMBER(20),
   ACTION_DATE        DATE,
   ACTION_TYPE_ID     NUMBER(20),
   OLD_SALARY         NUMBER(20),
   NEW_SALARY         NUMBER(20),
   OLD_POSSITION      VARCHAR2(50 CHAR),
   NEW_POSSITION      VARCHAR2(50 CHAR)
);

ALTER TABLE EMPLOYEES_ACTIONS
   ADD CONSTRAINT FK_EMPLOYEE_REFERENCE_ACTION_T FOREIGN KEY (ACTION_TYPE_ID)
      REFERENCES ACTION_TYPES (ACTION_TYPE_ID);

ALTER TABLE EMPLOYEES_ACTIONS
   ADD CONSTRAINT FK_EMPLOYEE_REFERENCE_EMPLOYEE FOREIGN KEY (EMP_ID)
      REFERENCES EMPLOYEES (EMP_ID);


GRANT DELETE,INSERT,UPDATE,SELECT ON EMPLOYEES_ACTIONS TO u_dw_cleansing;