--------------------------------------------------------
--  File created - Wednesday-August-07-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TMP_VEHICLES
--------------------------------------------------------

  CREATE TABLE "TMP_VEHICLES" 
   (	"VEHICLE_ID" NUMBER(32,0), 
	"VEHICLE_TYPE_ID" VARCHAR2(32), 
	"VEHICLE_DESC" VARCHAR2(200), 
	"VEHICLE_PRICE" NUMBER(9,2)
   ) ;
/
REM INSERTING into TMP_VEHICLES
SET DEFINE OFF;
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (1,'1','A 160 CDI Limousine',25882.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (2,'1','A 180 CDI Limousine',26834.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (3,'1','A 180 CDI BlueEFFICIENCY Edition Limousine',27310.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (4,'1','A 180 CDI DCT Limousine',29000.3);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (5,'1','A 200 CDI Limousine',28143.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (6,'1','A 220 CDI Limousine',34093.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (7,'1','A 180 Limousine',24335.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (8,'1','A 180 BlueEFFICIENCY Edition Limousine',24811.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (9,'1','A 200 Limousine',27370);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (10,'1','A 250 Limousine',33855.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (11,'1','A 250 Sport Limousine',37752.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (12,'1','A 250 4MATIC Limousine',36057);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (13,'1','A 45 AMG Limousine',49682.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (14,'2','B 200 Natural Gas Drive Sports Tourer',32368);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (15,'2','B 160 CDI Sports Tourer',27310.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (16,'2','B 180 CDI DCT Sports Tourer',30428.3);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (17,'2','B 180 CDI Sports Tourer',28262.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (18,'2','B 180 CDI BlueEFFICIENCY Edition Sports Tourer',28738.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (19,'2','B 200 CDI Sports Tourer',30493.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (20,'2','B 220 CDI Sports Tourer',35610.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (21,'2','B 180 Sports Tourer',26685.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (22,'2','B 200 Sports Tourer',28619.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (23,'2','B 220 4MATIC Sports Tourer',33230.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (24,'2','B 250 Sports Tourer',34718.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (25,'3','C 180 CDI Limousine',33349.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (26,'3','C 200 CDI Limousine',35283.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (27,'3','C 220 CDI Limousine',37544.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (28,'3','C 220 CDI BlueEFFICIENCY Edition Limousine',37544.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (29,'3','C 220 CDI 4MATIC Limousine',42304.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (30,'3','C 250 CDI Limousine',39805.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (31,'3','C 250 CDI 4MATIC Limousine',44565.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (32,'3','C 300 CDI 4MATIC Limousine',48314);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (33,'3','C 350 CDI Limousine',48314);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (34,'3','C 180 Limousine',33230.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (35,'3','C 200 Limousine',35402.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (36,'3','C 250 Limousine',40043.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (37,'3','C 350 Limousine',47302.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (38,'3','C 350 4MATIC Limousine',49682.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (39,'3','C 63 AMG Limousine',72233);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (40,'4','CL 500 Coupe',120606.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (41,'4','CL 500 4MATIC Coupe',125723.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (42,'4','CL 600 Coupe',165053);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (43,'4','CL 63 AMG Coupe',163149);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (44,'4','CL 65 AMG Coupe',230205.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (45,'5','CLA 200 CDI Coupe',33677);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (46,'5','CLA 220 CDI Coupe',37990.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (47,'5','CLA 180 Coupe',28976.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (48,'5','CLA 180 BlueEFFICIENCY Edition Coupe',28976.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (49,'5','CLA 200 Coupe',31862.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (50,'5','CLA 250 Coupe',38675);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (51,'5','CLA 250 4MATIC Coupe',40876.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (52,'5','CLA 45 AMG 4MATIC Coupe',56078.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (53,'6','CLS 250 CDI Coupe',59857);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (54,'6','CLS 350 CDI Coupe',63724.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (55,'6','CLS 350 BlueTEC Coupe',65152.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (56,'6','CLS 350 CDI 4MATIC Coupe',66461.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (57,'6','CLS 350 BlueTEC 4MATIC Coupe',67889.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (58,'6','CLS 350 Coupe',64914.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (59,'6','CLS 500 Coupe',80920);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (60,'6','CLS 500 4MATIC Coupe',83657);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (61,'6','CLS 63 AMG Coupe',116203.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (62,'6','CLS 63 AMG 4MATIC Coupe',120130.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (63,'6','CLS 63 AMG S 4MATIC Coupe',131078.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (64,'7','E 200 CDI Limousine',40430.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (65,'7','E 220 CDI Limousine',43286.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (66,'7','E 220 BlueTEC BlueEfficiency Edition Limousine',46558.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (67,'7','E 250 CDI Limousine',46320.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (68,'7','E 250 CDI 4MATIC Limousine',51556.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (69,'7','E 300 BlueTEC Limousine',51973.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (70,'7','E 300 BlueTEC HYBRID Limousine',52449.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (71,'7','E 350 BlueTEC Limousine',54710.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (72,'7','E 350 BlueTEC 4MATIC Limousine',57447.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (73,'7','E 200 Limousine',41917.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (74,'7','E 200 Natural Gas Drive Limousine',47808.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (75,'7','E 250 Limousine',46975.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (76,'7','E 300 Limousine',51229.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (77,'7','E 300 4MATIC Limousine',53966.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (78,'7','E 350 Limousine',53996.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (79,'7','E 350 4MATIC Limousine',56733.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (80,'7','E 400 Limousine',56019.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (81,'7','E 400 4MATIC Limousine',58756.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (82,'7','E 500 Limousine',70656.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (83,'7','E 500 4MATIC Limousine',73393.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (84,'7','E 63 AMG Limousine',103054);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (85,'7','E 63 AMG 4MATIC Limousine',106981);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (86,'7','E 63 AMG S 4MATIC Limousine',118405);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (87,'8','G 350 BlueTEC',86025.1);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (88,'8','G 500',100840.6);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (89,'8','G 63 AMG',138635);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (90,'8','G 65 AMG',266322);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (91,'9','GL 350 BlueTEC 4MATIC Off-Roader',73125.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (92,'9','GL 500 4MATIC Off-Roader',95438);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (93,'9','GL 63 AMG 4MATIC Off-Roader',131316.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (94,'10','GLK 200 CDI',36652);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (95,'10','GLK 220 CDI',38794);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (96,'10','GLK 220 CDI 4MATIC',43256.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (97,'10','GLK 220 BlueTEC 4MATIC',44684.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (98,'10','GLK 250 BlueTEC 4MATIC',46677.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (99,'10','GLK 350 CDI 4MATIC',50694);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (100,'10','GLK 250 4MATIC',44149);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (101,'10','GLK 350 4MATIC',51586.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (102,'11','ML 250 BlueTEC 4MATIC Off-Roader',55989.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (103,'11','ML 350 BlueTEC 4MATIC Off-Roader',59559.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (104,'11','ML 350 4MATIC Off-Roader',57715);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (105,'11','ML 500 4MATIC Off-Roader',75743.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (106,'11','ML 63 AMG 4MATIC Off-Roader',109777.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (107,'12','S 350 BlueTEC Limousine',79789.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (108,'12','S 350 BlueTEC Limousine (langer Radstand)',85323);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (109,'12','S 400 HYBRID Limousine',85204);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (110,'12','S 400 HYBRID Limousine (langer Radstand)',91094.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (111,'12','S 500 Limousine',104601);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (112,'12','S 500 Limousine (langer Radstand)',107635.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (113,'12','S 500 4MATIC Limousine',108409);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (114,'12','S 500 4MATIC Limousine (langer Radstand)',111443.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (115,'12','S 63 AMG Limousine',149880.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (116,'12','S 63 AMG 4MATIC Limousine (langer Radstand)',152617.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (117,'13','SL 350 Roadster',94962);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (118,'13','SL 500 Roadster',118821.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (119,'13','SL 63 AMG Roadster',159400.5);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (120,'13','SL 65 AMG Roadster',237643);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (121,'14','SLK 250 CDI Roadster',39894.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (122,'14','SLK 200 Roadster',39180.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (123,'14','SLK 250 Roadster',42334.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (124,'14','SLK 350 Roadster',52925.25);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (125,'14','SLK 55 AMG Roadster',73214.75);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (126,'15','SLS AMG Coupe',186830);
Insert into TMP_VEHICLES (VEHICLE_ID,VEHICLE_TYPE_ID,VEHICLE_DESC,VEHICLE_PRICE) values (127,'15','SLS AMG GT Coupe',204680);
commit;
