--DROP TABLE DIM_GEN_PERIODS CASCADE CONSTRAINTS;
CREATE TABLE DIM_GEN_PERIODS
(
	PER_SURR_ID     NUMBER(8) NOT NULL,
	PER_ID          NUMBER(8) ,
	PER_DESC        VARCHAR2(50) ,
	PER_BEGIN       DATE ,
	PER_END         DATE ,
	PER_LEVEL_CODE  VARCHAR2(20) ,
	INSERT_DT       DATE 
);

GRANT DELETE,INSERT,UPDATE,SELECT ON DIM_GEN_PERIODS TO u_sal_cl;


